---
title       : Developing Data Products, Week 4 Assignment
subtitle    : Shiny Application
author      : Enrico
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {selfcontained, standalone, draft}
knit        : slidify::knit2slides
---

## Shiny Application: Objectives  

Obiectives of the application  
- Practise the mechanisms of shiny useful in real applications, even if not taught in the course  
  - *ex. update Web GUI when user code, rather than a widget, changes a value*  
- Be simple, easy to understand for users/reviewers, use few resourses  
- Focus on learning&practising Shiny mechanisms.  
So instead of building a nice looking practically useful app with many widgets but performing a **single** hardcoded computation (ex depression test, calculating an index) I built and app performing different  statistical functions that allows to choose to which variables apply them (simple functions, it's an exercise after all)  
- Apply the points above in an application for which time availble is relatively short

The application is [here](https://enrico200165.shinyapps.io/devdataprodw4/), the user doc is [here](http://enrico200165.github.io/dataproductsslides/appdocumentation.html)  


--- .class #id 

## Application Fuctionalities
<br />
Allows to run statistical functions (names, ncol, mean ...)  
  - on whole dataframe <b>or</b>  
  - on the variable chosen by the user as the "x" variable  

<br />
Displays a scatterplot of <b>mtcars</b> data set, for any couple of variables **chosen by the user**.  
Shiny GUI elements are used  
- to select which are the two variables to plot (the y, the x)  
- to control details of the plot (smooth type, if any; point size)  

--- .class #id 
## Application Structure
The application is structured in 3 files  
-  The usual server.R and ui.R  
- <b>backend.R</b>  

backend.R decouples the (minimal) business logic from the GUI; it contains all and only non-GUI code.  
This basic good practise, in a real application, would allow to test the business logic on its own, independently from the GUI



--- .class #id 

## Additional Remarks

To keep together the plot options (managed by GUI widgets) a simple class was created, 
```{r setup, eval = FALSE, echo = TRUE, message = FALSE, warning = FALSE, tidy = FALSE}
setClass("plotParsClass",
  slots = c(regrSmoot = "character", pointSize = "numeric"))
plotPars = new("plotParsClass")
plotPars@pointSize <- 4 # in real app would get value from
# input$pointSize  in turn from sliderInput("pointSize", ...)
cat(plotPars@pointSize)
```  
  
<br />  
The debug messages printed to the web GUI and the automatic updating of the internal status message, was implemented using [reactiveValues()] (https://shiny.rstudio.com/reference/shiny/latest/reactiveValues.html) that gives to "normal" values properties similar to those of the GUI widgets, ie automatic update of the GUI (via the server) when a value is changed by the not by a GUI widget but by the programmer's code.

--- .class #id
